In [1]:
#### Working with numbers and mathematics
##### Numpy

In [2]:
#--------------------------------------------
# Import the Numpy libraries
#--------------------------------------------
import numpy as np

In [3]:
#--------------------------------------------
# Arrays
#--------------------------------------------
n=np.arange(27) # - Index starts at zero
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
print (n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [6]:
#--------------------------------------------
# Multi-Dimensional Arrays
#
#  This reshape command will change the one
#  dimensional array (1 row, 27 cols) to
#  a two dimensional array (3 rows, 9 cols)
#--------------------------------------------
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
# Three dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
#--------------------------------------------------
#  Creating an array from a list
#--------------------------------------------------
m = np.asarray([[123,12,123,12,33], [], []])
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [9]:
print (m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


In [10]:
type (m)

numpy.ndarray

### Working with OpenCV

In [11]:
import cv2 # Converts images to an array

In [12]:
#------------------------------------------------
# Set full file path names
#------------------------------------------------
folder_name = 'C:/Users/jrwel/Documents/Udemy/Python Mega Course/Data/'
file_name = 'smallgray.png'
image_file = folder_name + file_name

GRAY_SCALE = 0
BGR_SCALE  = 1

In [13]:
im_g=cv2.imread(image_file, GRAY_SCALE)  # - Read image file 0=gray scale, 1=bgr (blue-green-red scale)
im_g  # 3 rows by 5 columns (pixels) for our small image
      # each value is the intensity of the white/black shade
      # 255 = Pure white

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
im_g=cv2.imread(image_file, BGR_SCALE)  # - Read image file 0=gray scale, 1=bgr (blue-green-red scale)
im_g  # 3 dimensional array with 3 rows by 5 columns (pixels) for our small image 
      # the arrays are for the intensity of the blue - green - red shades

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [15]:
file_name = "newsmallgray.png"
new_image_file = folder_name + file_name
cv2.imwrite(new_image_file, im_g)

True

#### Indexing and slicing numpy array

In [16]:
a=[1,2,3]
a[0:2]

[1, 2]

In [17]:
im_g=cv2.imread(image_file, GRAY_SCALE)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [19]:
im_g[0:2, 2:4]  # Will get 104,121 and 255,255 from the im_g array. (rows 0 and 1, columns 2 and 3)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [20]:
im_g.shape

(3, 5)

In [21]:
im_g[:,2:4] # All rows, columns 2 and 3

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [22]:
im_g[2,4]

182

In [23]:
for i in im_g:  # i is row number
    print (i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
#----------------------------------------
# Transpose the array and iterate thru it 
# if you want to process the columns
#----------------------------------------
for i in im_g.T:  # i is column number of original array
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
#----------------------------------------
# Use flat command to process each
# cell of the array
#----------------------------------------
for i in im_g.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [30]:
#------------------------------------------------------
# Concatenating numpy arrays
#   Horizontal stacking
#   Must have same dimensions
#------------------------------------------------------
im_big = np.hstack((im_g, im_g)) # Use a tuple of numpy arrays - can be same or different
im_big

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
print (im_big)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [32]:
#------------------------------------------------------
# Concatenating numpy arrays
#   Vertical stacking
#   Must have same dimensions
#------------------------------------------------------
im_big = np.vstack((im_g, im_g)) # Use a tuple of numpy arrays - can be same or different
im_big

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [34]:
lst = np.hsplit(im_big, 3)
#
# will get error, must be equally divisible by the argument number (3)
#

ValueError: array split does not result in an equal division

In [35]:
lst = np.hsplit(im_big, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [37]:
lst=np.vsplit(im_big,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]